"""add thread_id to users

Revision ID: 7cd5d4e2ccfd
Revises: 128fcd26545e
Create Date: 2026-02-22 01:54:18.671805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cd5d4e2ccfd'
down_revision: Union[str, Sequence[str], None] = '128fcd26545e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('thread_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'thread_id')
    # ### end Alembic commands ###
